# Generated by Django 5.0.1 on 2024-01-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_item_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paypal_charge_id',
            field=models.CharField(choices=[('S', 'S'), ('P', 'P')], default='P', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(choices=[('S', 'S'), ('P', 'P')], default='S', max_length=50),
        ),
    ]
