# Generated by Django 5.0.1 on 2024-01-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_payment_paypal_charge_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('P', 'P'), ('', '')], default='S', max_length=50),
        ),
    ]
